### ISSUE TITLE
Alsa output device for streaming from PC is hard coded

### ISSUE THREAD

**Issue by henkelis** [henkelis/sonospy#62]
The alsa device parameter to parec in transcode.py is hardcoded. This needs to be either an ini setting or captured at install time.

For now, get it with:

```
pactl list | grep -A2 'Source #' | grep 'Name: ' | cut -d" " -f2
```

and copy it into transcode.py

**Comment by ianmacd** [comment]
An .ini setting might mean that some people never manage to figure out what to set it to. Perhaps the .ini setting could override a best-guess default in the code.

I probably could have saved you some time with this, as I've had to figure out exactly the same thing with vlc before.

I use the following to get the device:

```
DEVICE=$( pactl list | grep -A 2 'Source #' |
           sed -ne 's/^.*Name: \(.\+\.monitor\)$/\1/p' |
           grep -iv headset | head -n 1 )
```

The **sed** pipe pulls out only the monitors and the second **grep** removes any headset devices from the list.

In my case, the stream would otherwise be redirected to the mono headset that I use for Skype and other such programs, instead of to the sound card. I'm guessing that most people wouldn't want to do that.

If anyone has multiple sound cards, the above pipeline would pick the first one, but it's an improvement on what's currently hard-coded.
