### ISSUE TITLE
Sonos Queue

### ISSUE THREAD

**Issue by nlagaros** [henkelis/sonospy#67]
Via the web interface, the Sonos queue is no longer listed. 

Also, If I select a Sonos Playlist and choose the "Play Now And Queue" option, I would expect the following:
- all tracks in the playlist to be added to the end of the queue (this works, but is not displayed)
- first song in playlist plays (this works)
- Sonos continues to play each subsequent track in the queue (this does not work)

I see that the queue is in a non-active state on the Sonos ZonePlayer. Not sure if I am not understanding what should happen or calling sonospy incorrectly.

**Comment by henkelis** [comment]
Re the queue - in the web interface the queue is associated with the renderer rather than the server. If you select the zone in the renderer list the queue is displayed.

Re playing Sonos Playlists - I add the playlist entries one-by-one to the queue, rather than as a playlist, which is probably why you don't get the effect you desire. I'll have a look at it.

**Comment by nlagaros** [comment]
Thanks Mark.  My biggest issue right now is with the brisa integration.  There is a threading bug that was addressed in the latest release.  I poll multiple zoneplayers on a timer and see that threads increase like mad until the pycpoint crashes.
